# Generated by Django 6.1.1 on 2026-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المريض')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='رقم الهاتف')),
                ('gender', models.CharField(choices=[('MALE', 'ذكر'), ('أنثى', 'أنثى')], default='MALE', max_length=10, verbose_name='الجنس')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات عامة')),
                ('medical_history', models.TextField(blank=True, default='', verbose_name='التاريخ المرضي والحساسية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
    ]
