# Generated by Django 6.1.1 on 2026-10-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='رقم الهاتف'),
        ),
    ]
