# Generated by Django 6.1.1 on 2026-10-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_user_is_approved_alter_user_role_user_clinic'),
        ('patients', '0002_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.clinic', verbose_name='العيادة'),
        ),
    ]
