# Generated by Django 6.1.1 on 2026-10-09 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العيادة')),
                ('invite_code', models.CharField(max_length=20, unique=True, verbose_name='كود انضمام المساعدين')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف العيادة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='عنوان العيادة')),
                ('plan_name', models.CharField(default='الاشتراك الشهري الاحترافي', max_length=100, verbose_name='اسم الباقة')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='قيمة الاشتراك الشهري')),
                ('subscription_status', models.CharField(choices=[('ACTIVE', 'نشط'), ('TRIAL', 'تجريبي'), ('EXPIRED', 'منتهي'), ('SUSPENDED', 'معلق')], default='ACTIVE', max_length=20, verbose_name='حالة الاشتراك')),
                ('subscription_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بدء الاشتراك')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='العيادة نشطة ومفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='تمت الموافقة وتفعيل الحساب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SAAS_ADMIN', 'مدير المنصة (SaaS)'), ('DOCTOR', 'طبيب'), ('ASSISTANT', 'مساعد / استقبال')], default='ASSISTANT', max_length=20, verbose_name='الدور الوظيفي'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.clinic', verbose_name='العيادة التابع لها'),
        ),
    ]
