# Generated by Django 6.1.1 on 2026-10-09 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_user_is_approved_alter_user_role_user_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='subscription_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ بدء الاشتراك'),
        ),
    ]
