# Generated by Django 6.1.1 on 2026-09-26 13:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المبلغ الإجمالي الأصلي')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة الخصم (VIP / الحبايب)')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المسدد / المدفوع')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات الفاتورة والخصم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointments.appointment', verbose_name='الكشف / الموعد')),
            ],
            options={
                'verbose_name': 'فاتورة / سند مالي',
                'verbose_name_plural': 'الفواتير والسندات',
                'ordering': ['-created_at'],
            },
        ),
    ]
