# Generated by Django 6.1.1 on 2026-10-09 08:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_unique_together_and_more'),
        ('billing', '0001_initial'),
        ('patients', '0002_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الخدمة / الإجراء')),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='السعر الافتراضي')),
                ('is_common', models.BooleanField(default=False, verbose_name='إجراء شائع يظهر كزر سريع للطبيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خدمة / إجراء',
                'verbose_name_plural': 'الخدمات والإجراءات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة الخصم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات الفاتورة'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'مقدم / حجز مبدئي'), ('CHECKOUT', 'سداد عند الخروج'), ('DEBT_SETTLEMENT', 'سداد مديونية سابقة'), ('OTHER', 'دفع نقدي')], default='CHECKOUT', max_length=30, verbose_name='نوع الدفع')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment', verbose_name='الموعد المرتبط')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الإجراء')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='appointments.appointment', verbose_name='الموعد / الجلسة')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_procedures', to='billing.service', verbose_name='الخدمة المرتبطة')),
            ],
            options={
                'verbose_name': 'إجراء الجلسة',
                'verbose_name_plural': 'إجراءات الجلسة',
                'ordering': ['created_at'],
            },
        ),
    ]
