# Generated by Django 6.1.1 on 2026-09-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('GENERAL_CHECKUP', 'كشف عام'), ('ORTHO_NEW_FIT', 'تركيب تقويم جديد'), ('ORTHO_FOLLOWUP', 'متابعة تقويم')], default='GENERAL_CHECKUP', max_length=30, verbose_name='نوع الزيارة')),
                ('shift', models.CharField(choices=[('MORNING', 'صباحي (9:00 ص - 2:00 م)'), ('EVENING', 'مسائي (5:00 م - 10:00 م)')], default='MORNING', max_length=20, verbose_name='الشيفت')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('queue_number', models.PositiveIntegerField(verbose_name='رقم الدور')),
                ('status', models.CharField(choices=[('WAITING', 'في الانتظار'), ('WITH_DOCTOR', 'مع الطبيب'), ('COMPLETED', 'تم الكشف'), ('CANCELLED', 'ملغي')], default='WAITING', max_length=20, verbose_name='الحالة')),
                ('is_dawn_walkin', models.BooleanField(default=False, verbose_name='كشف فجر / فوري (كوتة محجوزة)')),
                ('doctor_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الطبيب والتشخيص')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد / كشف',
                'verbose_name_plural': 'المواعيد والكشوفات',
                'ordering': ['visit_date', 'queue_number'],
                'unique_together': {('visit_date', 'shift', 'queue_number')},
            },
        ),
    ]
