# Generated by Django 6.1.1 on 2026-10-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='الساعة / وقت الموعد'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('GENERAL_CHECKUP', 'كشف'), ('FOLLOWUP_CHECKUP', 'متابعة كشف'), ('ORTHO_NEW_FIT', 'تركيب تقويم'), ('ORTHO_FOLLOWUP', 'متابعة تقويم')], default='GENERAL_CHECKUP', max_length=30, verbose_name='نوع الزيارة'),
        ),
    ]
