# Generated by Django 6.1.1 on 2026-10-09 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinic_user_is_approved_alter_user_role_user_clinic'),
        ('appointments', '0002_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.clinic', verbose_name='العيادة'),
        ),
    ]
